### ISSUE TITLE
xnviewmp fails to start

### ISSUE THREAD

**Issue by Kalle72** [karolgrudzinski/c2p-overlay#1]
Hello,

thanks for bringing xnviewmp to gentoo!!! Yesterday I installed it, but unfortunately it will not start. 

The error message is:
This application failed to start because it could not find or load the Qt platform plugin "xcb".

I checked my qtgui installation but the xcb-flag is active:
[ebuild   R    ] dev-qt/qtgui-5.5.1-r1:5::gentoo  USE="dbus gif jpeg png udev xcb -accessibility -debug -egl -eglfs -evdev -gles2 -gtkstyle -ibus -libinput {-test} -tslib -tuio" 0 KiB

Any ideas or suggestions what the problem could be?

Best regards 
Kalle

**Comment by karolgrudzinski** [comment]
Does removing file /opt/XnView/qt.conf fixes this?

**Comment by Kalle72** [comment]
Thanks, it solves the problem!
