### ISSUE TITLE
firefox-59.0.1 fails

### ISSUE THREAD

**Issue by sophietheopossum** [karolgrudzinski/c2p-overlay#12]
this seems to be due to a missing eclass. see #11 for a possible solution

**Comment by karolgrudzinski** [comment]
Wow, I didn't know anybody uses this overlay. And Firefox 59 is a pretty old version. I don't use Gentoo anymore so I'm planning to archive (or delete) this repo is the near future.

**Comment by sophietheopossum** [comment]
ahhh okay. surprisingly this is the only overlay with xnviewmp available. i only said about the firefox because i keep getting warnings filling up my console about the missing eclass. if you want i have an overlay, i could probably move them over then see about getting this overlay removed from layman for now. (except for a few of the ebuilds which now seem to have official versions that are identical)

**Comment by karolgrudzinski** [comment]
I've also received an email from Gentoo's Bugzilla so the best thing I can do now is to remove firefox ebuilds. I will leave overlay active for now, because there is some possibility that I will return to using Gentoo :).

**Comment by sophietheopossum** [comment]
sounds like a good plan if you aren't using them
